dist: trusty
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
  - '13'
before_script:
  - npm i codecov
  - npm run bootstrap -- --no-ci
  - npm run build
after_success:
  - npm run coverage
  - codecov
